# Generated by Django 5.1.5 on 2025-01-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quistion',
            new_name='Question',
        ),
    ]
